# # # Date: 06062024
# # # Description: 
services:
  webserver:                            # It will run the php codes to serve the web page
    # image: php:apache                 # This will use the image directly from docker without any mod.
    build:                              # Manually build the image
      context: .
      dockerfile: Dockerfile.custom     # Use the custom Dockerfile
    volumes:
      - "./dist/:/var/www/html"              #Syncs the development directory with the docker container without the need to re-compose and run 
    ports:
      - 80:80                           # for web page
      - 443:443
  db:                                   # It will be running the mariadb
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=kuberkosh_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
    volumes:
      - "/home/ani/Documents/Keeper/Code/vscode/HTML&CSS&JS/College/Project/KuberKosh/db:/docker-entrypoint-initdb.d"           #Sync db with dev. env. and docker so that we dont loose the database when docker is stopped.
      - "/home/ani/Documents/Keeper/Code/vscode/HTML&CSS&JS/College/Project/KuberKosh/db/data:/var/lib/mysql"                   # Persist MariaDB data
  phpmyadmin:                                               # It will provide the GUI environment to manage the db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306


